d/postinst: create parent directory for /etc/iproute2/rt_tables.d
As iproute2's postinst also deletes /etc/iproute2 if it's empty, which
then fails the mkdir of the sub-directory:

Reported-by: Fiona Ebner <f.ebner@proxmox.com>
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/debian/ifupdown2.postinst b/debian/ifupdown2.postinst
--- a/debian/ifupdown2.postinst
+++ b/debian/ifupdown2.postinst
@@ -112,7 +112,7 @@ case "$1" in
         chmod +x /usr/share/ifupdown2/__main__.py
         postinst_remove_diverts
         if [ ! -d /etc/iproute2/rt_tables.d ]; then
-            mkdir /etc/iproute2/rt_tables.d || echo "could not create /etc/iproute2/rt_tables.d"
+            mkdir -p /etc/iproute2/rt_tables.d || echo "could not create /etc/iproute2/rt_tables.d"
         fi
         if [ -z "$2" ] && [ ! -e /proxmox_install_mode ]; then
             proxmox_compatibility
